[package]
name = "dot_vox"
version = "3.1.0"
authors = ["David Edmonds <edmonds.d.r@gmail.com>"]
description = "A Rust library for loading MagicaVoxel .vox files."
license = "MIT"
keywords = ['voxel', 'MagicaVoxel', 'game', 'game-dev']
documentation = "https://docs.rs/dot_vox"
homepage = "https://docs.rs/dot_vox"
repository = "https://github.com/davidedmonds/dot_vox"
readme = "README.md"

[dependencies]
byteorder = "^1.0"
lazy_static = "^1.0"
log = "^0.4"
nom = "^3.0"

[dev-dependencies]
avow = "0.2.0"
env_logger = "^0.5"